# Generated by Django 5.0.1 on 2024-02-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_publisher_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default/logo.png', null=True, upload_to='avatars/'),
        ),
    ]
